name: Build Original ZMK firmware
on: 
  workflow_dispatch:
    inputs:
      build_matrix_path:
        description: "Path to the build matrix file"
        default: "og_zmk_config/build.yaml"
        required: false
        type: string
      config_path:
        description: "Path to the config directory"
        default: "og_zmk_config/config"
        required: false
        type: string
      fallback_binary:
        description: "Fallback binary format, if no *.uf2 file was built"
        default: "bin"
        required: false
        type: string
      archive_name:
        description: "Archive output file name"
        default: "firmware"
        required: false
        type: string

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: ${{ inputs.build_matrix_path }}
      config_path: ${{ inputs.config_path }} 
      fallback_binary: ${{ inputs.fallback_binary }} 
      archive_name: ${{ inputs.archive_name }} 
